version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: license_postgres
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local