version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: license_postgres
    environment:
      POSTGRES_DB: licensedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: